/*
 * SPDX-FileCopyrightText: Copyright (C) 2025 Altera Corporation
 *
 * SPDX-License-Identifier: MIT-0
 *
 * Header file for I3C register definitions
 */
#ifndef __SOCFPGA_I3C_REGS_H__
#define __SOCFPGA_I3C_REGS_H__
/* Device Control Register */
#define I3C_DEVICE_CTRL                    0x0000U
/* Device Address Register */
#define I3C_DEVICE_ADDR                    0x0004U
/* Hardware Capability register */
#define I3C_HW_CAPABILITY                  0x0008U
/* COMMAND_QUEUE_PORT */
#define I3C_COMMAND_QUEUE_PORT             0x000CU
/* RESPONSE_QUEUE_PORT */
#define I3C_RESPONSE_QUEUE_PORT            0x0010U
/* Transmit Data Port Register */
#define I3C_TX_DATA_PORT                   0x0014U
/* Receive Data Port Register */
#define I3C_RX_DATA_PORT                   0x0014U
/* In-Band Interrupt Queue Status Register */
#define I3C_IBI_QUEUE_STATUS               0x0018U
/* In-Band Interrupt Queue Data Register */
#define I3C_IBI_QUEUE_DATA                 0x0018U
/* Queue Threshold Control Register */
#define I3C_QUEUE_THLD_CTRL                0x001CU
/* Data Buffer Threshold Control Register */
#define I3C_DATA_BUFFER_THLD_CTRL          0x0020U
/* IBI Queue Control Register */
#define I3C_IBI_QUEUE_CTRL                 0x0024U
/* Reset Control Register */
#define I3C_RESET_CTRL                     0x0034U
/* Slave Event Status Register */
#define I3C_SLV_EVENT_STATUS               0x0038U
/* Interrupt Status Register */
#define I3C_INTR_STATUS                    0x003CU
/* Interrupt Status Enable Register */
#define I3C_INTR_STATUS_EN                 0x0040U
/* Interrupt Signal Enable Register */
#define I3C_INTR_SIGNAL_EN                 0x0044U
/* Interrupt Force Enable Register */
#define I3C_INTR_FORCE                     0x0048U
/* Queue Status Level Register */
#define I3C_QUEUE_STATUS_LEVEL             0x004CU
/* Data Buffer Status Level Register */
#define I3C_DATA_BUFFER_STATUS_LEVEL       0x0050U
/* Present State Register */
#define I3C_PRESENT_STATE                  0x0054U
/* Pointer for Device Address Table Registers */
#define I3C_DEVICE_ADDR_TABLE_POINTER      0x005CU
/* Pointer for Device Characteristics Table */
#define I3C_DEV_CHAR_TABLE_POINTER         0x0060U
/* Pointer for Vendor specific Registers */
#define I3C_VENDOR_SPECIFIC_REG_POINTER    0x006CU
/* Device Control Extended Register */
#define I3C_DEVICE_CTRL_EXTENDED           0x00B0U
/* SCL I3C Open Drain Timing Register */
#define I3C_SCL_I3C_OD_TIMING              0x00B4U
/* SCL I3C Push Pull Timing Register */
#define I3C_SCL_I3C_PP_TIMING              0x00B8U
/* SCL I2C Fast Mode Timing Register */
#define I3C_SCL_I2C_FM_TIMING              0x00BCU
/* SCL I2C Fast Mode Plus Timing Register */
#define I3C_SCL_I2C_FMP_TIMING             0x00C0U
/* SCL Extended Low Count Timing Register */
#define I3C_SCL_EXT_LCNT_TIMING            0x00C8U
/* SCL Termination Bit Low count Timing Register */
#define I3C_SCL_EXT_TERMN_LCNT_TIMING      0x00CCU
/* SDA Hold and Mode Switch Delay Timing Register */
#define I3C_SDA_HOLD_SWITCH_DLY_TIMING     0x00D0U
/* Bus Free Timing Register */
#define I3C_BUS_FREE_AVAIL_TIMING          0x00D4U
/* DWC_mipi_i3c Version ID Register */
#define I3C_I3C_VER_ID                     0x00E0U
/* DWC_mipi_i3c Version Type Register */
#define I3C_I3C_VER_TYPE                   0x00E4U
/* DWC_mipi_i3c Queue Size Capability Register */
#define I3C_QUEUE_SIZE_CAPABILITY          0x00E8U
/* DEV_CHAR_TABLE1_LOC1 */
#define I3C_DEV_CHAR_TABLE1_LOC1           0x0200U
/* DEV_CHAR_TABLE1_LOC2 */
#define I3C_DEV_CHAR_TABLE1_LOC2           0x0204U
/* DEV_CHAR_TABLE1_LOC3 */
#define I3C_DEV_CHAR_TABLE1_LOC3           0x0208U
/* DEV_CHAR_TABLE1_LOC4 */
#define I3C_DEV_CHAR_TABLE1_LOC4           0x020CU
/* DEV_CHAR_TABLE2_LOC1 */
#define I3C_DEV_CHAR_TABLE2_LOC1           0x0210U
/* DEV_CHAR_TABLE2_LOC2 */
#define I3C_DEV_CHAR_TABLE2_LOC2           0x0214U
/* DEV_CHAR_TABLE2_LOC3 */
#define I3C_DEV_CHAR_TABLE2_LOC3           0x0218U
/* DEV_CHAR_TABLE2_LOC4 */
#define I3C_DEV_CHAR_TABLE2_LOC4           0x021CU
/* DEV_CHAR_TABLE3_LOC1 */
#define I3C_DEV_CHAR_TABLE3_LOC1           0x0220U
/* DEV_CHAR_TABLE3_LOC2 */
#define I3C_DEV_CHAR_TABLE3_LOC2           0x0224U
/* DEV_CHAR_TABLE3_LOC3 */
#define I3C_DEV_CHAR_TABLE3_LOC3           0x0228U
/* DEV_CHAR_TABLE3_LOC4 */
#define I3C_DEV_CHAR_TABLE3_LOC4           0x022CU
/* DEV_CHAR_TABLE4_LOC1 */
#define I3C_DEV_CHAR_TABLE4_LOC1           0x0230U
/* DEV_CHAR_TABLE4_LOC2 */
#define I3C_DEV_CHAR_TABLE4_LOC2           0x0234U
/* DEV_CHAR_TABLE4_LOC3 */
#define I3C_DEV_CHAR_TABLE4_LOC3           0x0238U
/* DEV_CHAR_TABLE4_LOC4 */
#define I3C_DEV_CHAR_TABLE4_LOC4           0x023CU
/* DEV_CHAR_TABLE5_LOC1 */
#define I3C_DEV_CHAR_TABLE5_LOC1           0x0240U
/* DEV_CHAR_TABLE5_LOC2 */
#define I3C_DEV_CHAR_TABLE5_LOC2           0x0244U
/* DEV_CHAR_TABLE5_LOC3 */
#define I3C_DEV_CHAR_TABLE5_LOC3           0x0248U
/* DEV_CHAR_TABLE5_LOC4 */
#define I3C_DEV_CHAR_TABLE5_LOC4           0x024CU
/* DEV_CHAR_TABLE6_LOC1 */
#define I3C_DEV_CHAR_TABLE6_LOC1           0x0250U
/* DEV_CHAR_TABLE6_LOC2 */
#define I3C_DEV_CHAR_TABLE6_LOC2           0x0254U
/* DEV_CHAR_TABLE6_LOC3 */
#define I3C_DEV_CHAR_TABLE6_LOC3           0x0258U
/* DEV_CHAR_TABLE6_LOC4 */
#define I3C_DEV_CHAR_TABLE6_LOC4           0x025CU
/* DEV_CHAR_TABLE7_LOC1 */
#define I3C_DEV_CHAR_TABLE7_LOC1           0x0260U
/* DEV_CHAR_TABLE7_LOC2 */
#define I3C_DEV_CHAR_TABLE7_LOC2           0x0264U
/* DEV_CHAR_TABLE7_LOC3 */
#define I3C_DEV_CHAR_TABLE7_LOC3           0x0268U
/* DEV_CHAR_TABLE7_LOC4 */
#define I3C_DEV_CHAR_TABLE7_LOC4           0x026CU
/* DEV_CHAR_TABLE8_LOC1 */
#define I3C_DEV_CHAR_TABLE8_LOC1           0x0270U
/* DEV_CHAR_TABLE8_LOC2 */
#define I3C_DEV_CHAR_TABLE8_LOC2           0x0274U
/* DEV_CHAR_TABLE8_LOC3 */
#define I3C_DEV_CHAR_TABLE8_LOC3           0x0278U
/* DEV_CHAR_TABLE8_LOC4 */
#define I3C_DEV_CHAR_TABLE8_LOC4           0x027CU
/* Device Address Table Location of Device1 */
#define I3C_DEV_ADDR_TABLE1_LOC1           0x0280U
/* Device Address Table Location 2U */
#define I3C_DEV_ADDR_TABLE2_LOC1           0x0284U
/* Device Address Table Location 3U */
#define I3C_DEV_ADDR_TABLE3_LOC1           0x0288U
/* Device Address Table Location 4U */
#define I3C_DEV_ADDR_TABLE4_LOC1           0x028CU
/* Device Address Table Location 5U */
#define I3C_DEV_ADDR_TABLE5_LOC1           0x0290U
/* Device Address Table Location 6U */
#define I3C_DEV_ADDR_TABLE6_LOC1           0x0294U
/* Device Address Table Location 7U */
#define I3C_DEV_ADDR_TABLE7_LOC1           0x0298U
/* Device Address Table Location 8U */
#define I3C_DEV_ADDR_TABLE8_LOC1           0x029CU
/* Device Address Table Location 9U */
#define I3C_DEV_ADDR_TABLE9_LOC1           0x02A0U
/* Device Address Table Location 10U */
#define I3C_DEV_ADDR_TABLE10_LOC1          0x02A4U
/* Device Address Table Location 11U */
#define I3C_DEV_ADDR_TABLE11_LOC1          0x02A8U

/* Bit fields of DEVICE_CTRL register */
#define I3C_DEVICE_CTRL_ENABLE_MASK \
    0x80000000U
#define I3C_DEVICE_CTRL_ENABLE_POS               31U
#define I3C_DEVICE_CTRL_RESUME_MASK \
    0x40000000U
#define I3C_DEVICE_CTRL_RESUME_POS               30U
#define I3C_DEVICE_CTRL_ABORT_MASK \
    0x20000000U
#define I3C_DEVICE_CTRL_ABORT_POS                29U
#define I3C_DEVICE_CTRL_DMA_ENABLE_MASK \
    0x10000000U
#define I3C_DEVICE_CTRL_DMA_ENABLE_POS           28U
#define I3C_DEVICE_CTRL_HOT_JOIN_CTRL_MASK \
    0x00000100U
#define I3C_DEVICE_CTRL_HOT_JOIN_CTRL_POS        8U
#define I3C_DEVICE_CTRL_I2C_SLAVE_PRESENT_MASK \
    0x00000080U
#define I3C_DEVICE_CTRL_I2C_SLAVE_PRESENT_POS    7U
#define I3C_DEVICE_CTRL_IBA_INCLUDE_MASK \
    0x00000001U
#define I3C_DEVICE_CTRL_IBA_INCLUDE_POS          0U

/* Bit fields of DEVICE_ADDR register */
#define I3C_DEVICE_ADDR_DYNAMIC_ADDR_VALID_MASK \
    0x80000000U
#define I3C_DEVICE_ADDR_DYNAMIC_ADDR_VALID_POS    31U
#define I3C_DEVICE_ADDR_DYNAMIC_ADDR_MASK \
    0x007F0000U
#define I3C_DEVICE_ADDR_DYNAMIC_ADDR_POS          16U

/* Bit fields of HW_CAPABILITY register */
#define I3C_HW_CAPABILITY_SLV_IBI_CAP_MASK \
    0x00080000U
#define I3C_HW_CAPABILITY_SLV_IBI_CAP_POS            19U
#define I3C_HW_CAPABILITY_SLV_HJ_CAP_MASK \
    0x00040000U
#define I3C_HW_CAPABILITY_SLV_HJ_CAP_POS             18U
#define I3C_HW_CAPABILITY_DMA_EN_MASK \
    0x00020000U
#define I3C_HW_CAPABILITY_DMA_EN_POS                 17U
#define I3C_HW_CAPABILITY_HDR_TX_CLOCK_PERIOD_MASK \
    0x0001F800U
#define I3C_HW_CAPABILITY_HDR_TX_CLOCK_PERIOD_POS    11U
#define I3C_HW_CAPABILITY_CLOCK_PERIOD_MASK \
    0x000007E0U
#define I3C_HW_CAPABILITY_CLOCK_PERIOD_POS           5U
#define I3C_HW_CAPABILITY_HDR_TS_EN_MASK \
    0x00000010U
#define I3C_HW_CAPABILITY_HDR_TS_EN_POS              4U
#define I3C_HW_CAPABILITY_HDR_DDR_EN_MASK \
    0x00000008U
#define I3C_HW_CAPABILITY_HDR_DDR_EN_POS             3U
#define I3C_HW_CAPABILITY_DEVICE_ROLE_CONFIG_MASK \
    0x00000007U
#define I3C_HW_CAPABILITY_DEVICE_ROLE_CONFIG_POS     0U

/* Bit fields of COMMAND_QUEUE_PORT register */
#define I3C_COMMAND_QUEUE_PORT_COMMAND_MASK \
    0xFFFFFFFFU
#define I3C_COMMAND_QUEUE_PORT_COMMAND_POS    0U

/* Bit fields of RESPONSE_QUEUE_PORT register */
#define I3C_RESPONSE_QUEUE_PORT_RESPONSE_MASK \
    0xFFFFFFFFU
#define I3C_RESPONSE_QUEUE_PORT_RESPONSE_POS    0U

/* Bit fields of TX_DATA_PORT register */
#define I3C_TX_DATA_PORT_TX_DATA_PORT_MASK \
    0xFFFFFFFFU
#define I3C_TX_DATA_PORT_TX_DATA_PORT_POS    0U

/* Bit fields of RX_DATA_PORT register */
#define I3C_RX_DATA_PORT_RX_DATA_PORT_MASK \
    0xFFFFFFFFU
#define I3C_RX_DATA_PORT_RX_DATA_PORT_POS    0U

/* Bit fields of IBI_QUEUE_STATUS register */
#define I3C_IBI_QUEUE_STATUS_IBI_STS_MASK \
    0xF0000000U
#define I3C_IBI_QUEUE_STATUS_IBI_STS_POS        28U
#define I3C_IBI_QUEUE_STATUS_IBI_ID_MASK \
    0x0000FF00U
#define I3C_IBI_QUEUE_STATUS_IBI_ID_POS         8U
#define I3C_IBI_QUEUE_STATUS_DATA_LENGTH_MASK \
    0x000000FFU
#define I3C_IBI_QUEUE_STATUS_DATA_LENGTH_POS    0U

/* Bit fields of IBI_QUEUE_DATA register */
#define I3C_IBI_QUEUE_DATA_IBI_DATA_MASK \
    0xFFFFFFFFU
#define I3C_IBI_QUEUE_DATA_IBI_DATA_POS    0U

/* Bit fields of QUEUE_THLD_CTRL register */
#define I3C_QUEUE_THLD_CTRL_IBI_STATUS_THLD_MASK \
    0xFF000000U
#define I3C_QUEUE_THLD_CTRL_IBI_STATUS_THLD_POS       24U
#define I3C_QUEUE_THLD_CTRL_IBI_DATA_THLD_MASK \
    0x00FF0000U
#define I3C_QUEUE_THLD_CTRL_IBI_DATA_THLD_POS         16U
#define I3C_QUEUE_THLD_CTRL_RESP_BUF_THLD_MASK \
    0x0000FF00U
#define I3C_QUEUE_THLD_CTRL_RESP_BUF_THLD_POS         8U
#define I3C_QUEUE_THLD_CTRL_CMD_EMPTY_BUF_THLD_MASK \
    0x000000FFU
#define I3C_QUEUE_THLD_CTRL_CMD_EMPTY_BUF_THLD_POS    0U

/*Threshold level for DATA_BUFFER_THLD_CTRL register*/
#define I3C_DATA_BUFFER_THLD_CTRL_LVL16               0x3U

/* Bit fields of DATA_BUFFER_THLD_CTRL register */
#define I3C_DATA_BUFFER_THLD_CTRL_RX_START_THLD_MASK \
    0x07000000U
#define I3C_DATA_BUFFER_THLD_CTRL_RX_START_THLD_POS        24U
#define I3C_DATA_BUFFER_THLD_CTRL_TX_START_THLD_MASK \
    0x00070000U
#define I3C_DATA_BUFFER_THLD_CTRL_TX_START_THLD_POS        16U
#define I3C_DATA_BUFFER_THLD_CTRL_RX_BUF_THLD_MASK \
    0x00000700U
#define I3C_DATA_BUFFER_THLD_CTRL_RX_BUF_THLD_POS          8U
#define I3C_DATA_BUFFER_THLD_CTRL_TX_EMPTY_BUF_THLD_MASK \
    0x00000007U
#define I3C_DATA_BUFFER_THLD_CTRL_TX_EMPTY_BUF_THLD_POS    0U

/* Bit fields of IBI_QUEUE_CTRL register */
#define I3C_IBI_QUEUE_CTRL_NOTIFY_SIR_REJECTED_MASK \
    0x00000008U
#define I3C_IBI_QUEUE_CTRL_NOTIFY_SIR_REJECTED_POS    3U
#define I3C_IBI_QUEUE_CTRL_NOTIFY_HJ_REJECTED_MASK \
    0x00000001U
#define I3C_IBI_QUEUE_CTRL_NOTIFY_HJ_REJECTED_POS     0U

/* Bit fields of RESET_CTRL register */
#define I3C_RESET_CTRL_IBI_QUEUE_RST_MASK \
    0x00000020U
#define I3C_RESET_CTRL_IBI_QUEUE_RST_POS     5U
#define I3C_RESET_CTRL_RX_FIFO_RST_MASK \
    0x00000010U
#define I3C_RESET_CTRL_RX_FIFO_RST_POS       4U
#define I3C_RESET_CTRL_TX_FIFO_RST_MASK \
    0x00000008U
#define I3C_RESET_CTRL_TX_FIFO_RST_POS       3U
#define I3C_RESET_CTRL_RESP_QUEUE_RST_MASK \
    0x00000004U
#define I3C_RESET_CTRL_RESP_QUEUE_RST_POS    2U
#define I3C_RESET_CTRL_CMD_QUEUE_RST_MASK \
    0x00000002U
#define I3C_RESET_CTRL_CMD_QUEUE_RST_POS     1U
#define I3C_RESET_CTRL_SOFT_RST_MASK \
    0x00000001U
#define I3C_RESET_CTRL_SOFT_RST_POS          0U

/* Bit fields of SLV_EVENT_STATUS register */
#define I3C_SLV_EVENT_STATUS_MWL_UPDATED_MASK \
    0x00000080U
#define I3C_SLV_EVENT_STATUS_MWL_UPDATED_POS       7U
#define I3C_SLV_EVENT_STATUS_MRL_UPDATED_MASK \
    0x00000040U
#define I3C_SLV_EVENT_STATUS_MRL_UPDATED_POS       6U
#define I3C_SLV_EVENT_STATUS_ACTIVITY_STATE_MASK \
    0x00000030U
#define I3C_SLV_EVENT_STATUS_ACTIVITY_STATE_POS    4U

/* Bit fields of INTR_STATUS register */
#define I3C_INTR_STATUS_TRANSFER_ERR_STS_MASK \
    0x00000200U
#define I3C_INTR_STATUS_TRANSFER_ERR_STS_POS       9U
#define I3C_INTR_STATUS_TRANSFER_ABORT_STS_MASK \
    0x00000020U
#define I3C_INTR_STATUS_TRANSFER_ABORT_STS_POS     5U
#define I3C_INTR_STATUS_RESP_READY_STS_MASK \
    0x00000010U
#define I3C_INTR_STATUS_RESP_READY_STS_POS         4U
#define I3C_INTR_STATUS_CMD_QUEUE_READY_STS_MASK \
    0x00000008U
#define I3C_INTR_STATUS_CMD_QUEUE_READY_STS_POS    3U
#define I3C_INTR_STATUS_IBI_THLD_STS_MASK \
    0x00000004U
#define I3C_INTR_STATUS_IBI_THLD_STS_POS           2U
#define I3C_INTR_STATUS_RX_THLD_STS_MASK \
    0x00000002U
#define I3C_INTR_STATUS_RX_THLD_STS_POS            1U
#define I3C_INTR_STATUS_TX_THLD_STS_MASK \
    0x00000001U
#define I3C_INTR_STATUS_TX_THLD_STS_POS            0U

/* Bit fields of INTR_STATUS_EN register */
#define I3C_INTR_STATUS_EN_TRANSFER_ERR_STS_EN_MASK \
    0x00000200U
#define I3C_INTR_STATUS_EN_TRANSFER_ERR_STS_EN_POS       9U
#define I3C_INTR_STATUS_EN_TRANSFER_ABORT_STS_EN_MASK \
    0x00000020U
#define I3C_INTR_STATUS_EN_TRANSFER_ABORT_STS_EN_POS     5U
#define I3C_INTR_STATUS_EN_RESP_READY_STS_EN_MASK \
    0x00000010U
#define I3C_INTR_STATUS_EN_RESP_READY_STS_EN_POS         4U
#define I3C_INTR_STATUS_EN_CMD_QUEUE_READY_STS_EN_MASK \
    0x00000008U
#define I3C_INTR_STATUS_EN_CMD_QUEUE_READY_STS_EN_POS    3U
#define I3C_INTR_STATUS_EN_IBI_THLD_STS_EN_MASK \
    0x00000004U
#define I3C_INTR_STATUS_EN_IBI_THLD_STS_EN_POS           2U
#define I3C_INTR_STATUS_EN_RX_THLD_STS_EN_MASK \
    0x00000002U
#define I3C_INTR_STATUS_EN_RX_THLD_STS_EN_POS            1U
#define I3C_INTR_STATUS_EN_TX_THLD_STS_EN_MASK \
    0x00000001U
#define I3C_INTR_STATUS_EN_TX_THLD_STS_EN_POS            0U

/* Bit fields of INTR_SIGNAL_EN register */
#define I3C_INTR_SIGNAL_EN_TRANSFER_ERR_SIGNAL_EN_MASK \
    0x00000200U
#define I3C_INTR_SIGNAL_EN_TRANSFER_ERR_SIGNAL_EN_POS       9U
#define I3C_INTR_SIGNAL_EN_TRANSFER_ABORT_SIGNAL_EN_MASK \
    0x00000020U
#define I3C_INTR_SIGNAL_EN_TRANSFER_ABORT_SIGNAL_EN_POS     5U
#define I3C_INTR_SIGNAL_EN_RESP_READY_SIGNAL_EN_MASK \
    0x00000010U
#define I3C_INTR_SIGNAL_EN_RESP_READY_SIGNAL_EN_POS         4U
#define I3C_INTR_SIGNAL_EN_CMD_QUEUE_READY_SIGNAL_EN_MASK \
    0x00000008U
#define I3C_INTR_SIGNAL_EN_CMD_QUEUE_READY_SIGNAL_EN_POS    3U
#define I3C_INTR_SIGNAL_EN_IBI_THLD_SIGNAL_EN_MASK \
    0x00000004U
#define I3C_INTR_SIGNAL_EN_IBI_THLD_SIGNAL_EN_POS           2U
#define I3C_INTR_SIGNAL_EN_RX_THLD_SIGNAL_EN_MASK \
    0x00000002U
#define I3C_INTR_SIGNAL_EN_RX_THLD_SIGNAL_EN_POS            1U
#define I3C_INTR_SIGNAL_EN_TX_THLD_SIGNAL_EN_MASK \
    0x00000001U
#define I3C_INTR_SIGNAL_EN_TX_THLD_SIGNAL_EN_POS            0U

/* Bit fields of INTR_FORCE register */
#define I3C_INTR_FORCE_TRANSFER_ERR_FORCE_EN_MASK \
    0x00000200U
#define I3C_INTR_FORCE_TRANSFER_ERR_FORCE_EN_POS       9U
#define I3C_INTR_FORCE_TRANSFER_ABORT_FORCE_EN_MASK \
    0x00000020U
#define I3C_INTR_FORCE_TRANSFER_ABORT_FORCE_EN_POS     5U
#define I3C_INTR_FORCE_RESP_READY_FORCE_EN_MASK \
    0x00000010U
#define I3C_INTR_FORCE_RESP_READY_FORCE_EN_POS         4U
#define I3C_INTR_FORCE_CMD_QUEUE_READY_FORCE_EN_MASK \
    0x00000008U
#define I3C_INTR_FORCE_CMD_QUEUE_READY_FORCE_EN_POS    3U
#define I3C_INTR_FORCE_IBI_THLD_FORCE_EN_MASK \
    0x00000004U
#define I3C_INTR_FORCE_IBI_THLD_FORCE_EN_POS           2U
#define I3C_INTR_FORCE_RX_THLD_FORCE_EN_MASK \
    0x00000002U
#define I3C_INTR_FORCE_RX_THLD_FORCE_EN_POS            1U
#define I3C_INTR_FORCE_TX_THLD_FORCE_EN_MASK \
    0x00000001U
#define I3C_INTR_FORCE_TX_THLD_FORCE_EN_POS            0U

/* Bit fields of QUEUE_STATUS_LEVEL register */
#define I3C_QUEUE_STATUS_LEVEL_IBI_STS_CNT_MASK \
    0x1F000000U
#define I3C_QUEUE_STATUS_LEVEL_IBI_STS_CNT_POS            24U
#define I3C_QUEUE_STATUS_LEVEL_IBI_BUF_BLR_MASK \
    0x00FF0000U
#define I3C_QUEUE_STATUS_LEVEL_IBI_BUF_BLR_POS            16U
#define I3C_QUEUE_STATUS_LEVEL_RESP_BUF_BLR_MASK \
    0x0000FF00U
#define I3C_QUEUE_STATUS_LEVEL_RESP_BUF_BLR_POS           8U
#define I3C_QUEUE_STATUS_LEVEL_CMD_QUEUE_EMPTY_LOC_MASK \
    0x000000FFU
#define I3C_QUEUE_STATUS_LEVEL_CMD_QUEUE_EMPTY_LOC_POS    0U

/* Bit fields of DATA_BUFFER_STATUS_LEVEL register */
#define I3C_DATA_BUFFER_STATUS_LEVEL_RX_BUF_BLR_MASK \
    0x00FF0000U
#define I3C_DATA_BUFFER_STATUS_LEVEL_RX_BUF_BLR_POS          16U
#define I3C_DATA_BUFFER_STATUS_LEVEL_TX_BUF_EMPTY_LOC_MASK \
    0x000000FFU
#define I3C_DATA_BUFFER_STATUS_LEVEL_TX_BUF_EMPTY_LOC_POS    0U

/* Bit fields of PRESENT_STATE register */
#define I3C_PRESENT_STATE_MASTER_IDLE_MASK \
    0x10000000U
#define I3C_PRESENT_STATE_MASTER_IDLE_POS              28U
#define I3C_PRESENT_STATE_CMD_TID_MASK \
    0x0F000000U
#define I3C_PRESENT_STATE_CMD_TID_POS                  24U
#define I3C_PRESENT_STATE_CM_TFR_ST_STS_MASK \
    0x003F0000U
#define I3C_PRESENT_STATE_CM_TFR_ST_STS_POS            16U
#define I3C_PRESENT_STATE_CM_TFR_STS_MASK \
    0x00003F00U
#define I3C_PRESENT_STATE_CM_TFR_STS_POS               8U
#define I3C_PRESENT_STATE_CURRENT_MASTER_MASK \
    0x00000004U
#define I3C_PRESENT_STATE_CURRENT_MASTER_POS           2U
#define I3C_PRESENT_STATE_SDA_LINE_SIGNAL_LEVEL_MASK \
    0x00000002U
#define I3C_PRESENT_STATE_SDA_LINE_SIGNAL_LEVEL_POS    1U
#define I3C_PRESENT_STATE_SCL_LINE_SIGNAL_LEVEL_MASK \
    0x00000001U
#define I3C_PRESENT_STATE_SCL_LINE_SIGNAL_LEVEL_POS    0U

/* Bit fields of DEVICE_ADDR_TABLE_POINTER register */
#define I3C_DEVICE_ADDR_TABLE_POINTER_DEV_ADDR_TABLE_DEPTH_MASK \
    0xFFFF0000U
#define I3C_DEVICE_ADDR_TABLE_POINTER_DEV_ADDR_TABLE_DEPTH_POS           16U
#define I3C_DEVICE_ADDR_TABLE_POINTER_P_DEV_ADDR_TABLE_START_ADDR_MASK \
    0x0000FFFFU
#define I3C_DEVICE_ADDR_TABLE_POINTER_P_DEV_ADDR_TABLE_START_ADDR_POS    0U

/* Bit fields of DEV_CHAR_TABLE_POINTER register */
#define I3C_DEV_CHAR_TABLE_POINTER_PRESENT_DEV_CHAR_TABLE_INDX_MASK \
    0x00380000U
#define I3C_DEV_CHAR_TABLE_POINTER_PRESENT_DEV_CHAR_TABLE_INDX_POS    19U
#define I3C_DEV_CHAR_TABLE_POINTER_DEV_CHAR_TABLE_DEPTH_MASK \
    0x0007F000U
#define I3C_DEV_CHAR_TABLE_POINTER_DEV_CHAR_TABLE_DEPTH_POS           12U
#define I3C_DEV_CHAR_TABLE_POINTER_P_DEV_CHAR_TABLE_START_ADDR_MASK \
    0x00000FFFU
#define I3C_DEV_CHAR_TABLE_POINTER_P_DEV_CHAR_TABLE_START_ADDR_POS    0U

/* Bit fields of VENDOR_SPECIFIC_REG_POINTER register */
#define I3C_VENDOR_SPECIFIC_REG_POINTER_P_VENDOR_REG_START_ADDR_MASK \
    0x0000FFFFU
#define I3C_VENDOR_SPECIFIC_REG_POINTER_P_VENDOR_REG_START_ADDR_POS    0U

/* Bit fields of DEVICE_CTRL_EXTENDED register */
#define I3C_DEVICE_CTRL_EXTENDED_DEV_OPERATION_MODE_MASK \
    0x00000003U
#define I3C_DEVICE_CTRL_EXTENDED_DEV_OPERATION_MODE_POS    0U

/* Bit fields of SCL_I3C_OD_TIMING register */
#define I3C_SCL_I3C_OD_TIMING_I3C_OD_HCNT_MASK \
    0x00FF0000U
#define I3C_SCL_I3C_OD_TIMING_I3C_OD_HCNT_POS    16U
#define I3C_SCL_I3C_OD_TIMING_I3C_OD_LCNT_MASK \
    0x000000FFU
#define I3C_SCL_I3C_OD_TIMING_I3C_OD_LCNT_POS    0U

/* Bit fields of SCL_I3C_PP_TIMING register */
#define I3C_SCL_I3C_PP_TIMING_I3C_PP_HCNT_MASK \
    0x00FF0000U
#define I3C_SCL_I3C_PP_TIMING_I3C_PP_HCNT_POS    16U
#define I3C_SCL_I3C_PP_TIMING_I3C_PP_LCNT_MASK \
    0x000000FFU
#define I3C_SCL_I3C_PP_TIMING_I3C_PP_LCNT_POS    0U

/* Bit fields of SCL_I2C_FM_TIMING register */
#define I3C_SCL_I2C_FM_TIMING_I2C_FM_HCNT_MASK \
    0xFFFF0000U
#define I3C_SCL_I2C_FM_TIMING_I2C_FM_HCNT_POS    16U
#define I3C_SCL_I2C_FM_TIMING_I2C_FM_LCNT_MASK \
    0x0000FFFFU
#define I3C_SCL_I2C_FM_TIMING_I2C_FM_LCNT_POS    0U

/* Bit fields of SCL_I2C_FMP_TIMING register */
#define I3C_SCL_I2C_FMP_TIMING_I2C_FMP_HCNT_MASK \
    0x00FF0000U
#define I3C_SCL_I2C_FMP_TIMING_I2C_FMP_HCNT_POS    16U
#define I3C_SCL_I2C_FMP_TIMING_I2C_FMP_LCNT_MASK \
    0x0000FFFFU
#define I3C_SCL_I2C_FMP_TIMING_I2C_FMP_LCNT_POS    0U

/* Bit fields of SCL_EXT_LCNT_TIMING register */
#define I3C_SCL_EXT_LCNT_TIMING_I3C_EXT_LCNT_4_MASK \
    0xFF000000U
#define I3C_SCL_EXT_LCNT_TIMING_I3C_EXT_LCNT_4_POS    24U
#define I3C_SCL_EXT_LCNT_TIMING_I3C_EXT_LCNT_3_MASK \
    0x00FF0000U
#define I3C_SCL_EXT_LCNT_TIMING_I3C_EXT_LCNT_3_POS    16U
#define I3C_SCL_EXT_LCNT_TIMING_I3C_EXT_LCNT_2_MASK \
    0x0000FF00U
#define I3C_SCL_EXT_LCNT_TIMING_I3C_EXT_LCNT_2_POS    8U
#define I3C_SCL_EXT_LCNT_TIMING_I3C_EXT_LCNT_1_MASK \
    0x000000FFU
#define I3C_SCL_EXT_LCNT_TIMING_I3C_EXT_LCNT_1_POS    0U

/* Bit fields of SCL_EXT_TERMN_LCNT_TIMING register */
#define I3C_SCL_EXT_TERMN_LCNT_TIMING_I3C_EXT_TERMN_LCNT_MASK \
    0x0000000FU
#define I3C_SCL_EXT_TERMN_LCNT_TIMING_I3C_EXT_TERMN_LCNT_POS    0U

/* Bit fields of SDA_HOLD_SWITCH_DLY_TIMING register */
#define I3C_SDA_HOLD_SWITCH_DLY_TIMING_SDA_TX_HOLD_MASK \
    0x00070000U
#define I3C_SDA_HOLD_SWITCH_DLY_TIMING_SDA_TX_HOLD_POS    16U

/* Bit fields of BUS_FREE_AVAIL_TIMING register */
#define I3C_BUS_FREE_AVAIL_TIMING_BUS_FREE_TIME_MASK \
    0x0000FFFFU
#define I3C_BUS_FREE_AVAIL_TIMING_BUS_FREE_TIME_POS    0U

/* Bit fields of I3C_VER_ID register */
#define I3C_I3C_VER_ID_I3C_VER_ID_MASK \
    0xFFFFFFFFU
#define I3C_I3C_VER_ID_I3C_VER_ID_POS    0U

/* Bit fields of I3C_VER_TYPE register */
#define I3C_I3C_VER_TYPE_I3C_VER_TYPE_MASK \
    0xFFFFFFFFU
#define I3C_I3C_VER_TYPE_I3C_VER_TYPE_POS    0U

/* Bit fields of QUEUE_SIZE_CAPABILITY register */
#define I3C_QUEUE_SIZE_CAPABILITY_IBI_BUF_SIZE_MASK \
    0x000F0000U
#define I3C_QUEUE_SIZE_CAPABILITY_IBI_BUF_SIZE_POS     16U
#define I3C_QUEUE_SIZE_CAPABILITY_RESP_BUF_SIZE_MASK \
    0x0000F000U
#define I3C_QUEUE_SIZE_CAPABILITY_RESP_BUF_SIZE_POS    12U
#define I3C_QUEUE_SIZE_CAPABILITY_CMD_BUF_SIZE_MASK \
    0x00000F00U
#define I3C_QUEUE_SIZE_CAPABILITY_CMD_BUF_SIZE_POS     8U
#define I3C_QUEUE_SIZE_CAPABILITY_RX_BUF_SIZE_MASK \
    0x000000F0U
#define I3C_QUEUE_SIZE_CAPABILITY_RX_BUF_SIZE_POS      4U
#define I3C_QUEUE_SIZE_CAPABILITY_TX_BUF_SIZE_MASK \
    0x0000000FU
#define I3C_QUEUE_SIZE_CAPABILITY_TX_BUF_SIZE_POS      0U

/* Bit fields of DEV_CHAR_TABLE1_LOC1 register */
#define I3C_DEV_CHAR_TABLE1_LOC1_LSB_PROVISIONAL_ID_MASK \
    0xFFFFFFFFU
#define I3C_DEV_CHAR_TABLE1_LOC1_LSB_PROVISIONAL_ID_POS    0U

/* Bit fields of DEV_CHAR_TABLE1_LOC2 register */
#define I3C_DEV_CHAR_TABLE1_LOC2_MSB_PROVISIONAL_ID_MASK \
    0x0000FFFFU
#define I3C_DEV_CHAR_TABLE1_LOC2_MSB_PROVISIONAL_ID_POS    0U

/* Bit fields of DEV_CHAR_TABLE1_LOC3 register */
#define I3C_DEV_CHAR_TABLE1_LOC3_BCR_MASK \
    0x0000FF00U
#define I3C_DEV_CHAR_TABLE1_LOC3_BCR_POS    8U
#define I3C_DEV_CHAR_TABLE1_LOC3_DCR_MASK \
    0x000000FFU
#define I3C_DEV_CHAR_TABLE1_LOC3_DCR_POS    0U

/* Bit fields of DEV_CHAR_TABLE1_LOC4 register */
#define I3C_DEV_CHAR_TABLE1_LOC4_DEV_DYNAMIC_ADDR_MASK \
    0x000000FFU
#define I3C_DEV_CHAR_TABLE1_LOC4_DEV_DYNAMIC_ADDR_POS    0U

/* Bit fields of DEV_CHAR_TABLE2_LOC1 register */
#define I3C_DEV_CHAR_TABLE2_LOC1_LSB_PROVISIONAL_ID_MASK \
    0xFFFFFFFFU
#define I3C_DEV_CHAR_TABLE2_LOC1_LSB_PROVISIONAL_ID_POS    0U

/* Bit fields of DEV_CHAR_TABLE2_LOC2 register */
#define I3C_DEV_CHAR_TABLE2_LOC2_MSB_PROVISIONAL_ID_MASK \
    0x0000FFFFU
#define I3C_DEV_CHAR_TABLE2_LOC2_MSB_PROVISIONAL_ID_POS    0U

/* Bit fields of DEV_CHAR_TABLE2_LOC3 register */
#define I3C_DEV_CHAR_TABLE2_LOC3_BCR_MASK \
    0x0000FF00U
#define I3C_DEV_CHAR_TABLE2_LOC3_BCR_POS    8U
#define I3C_DEV_CHAR_TABLE2_LOC3_DCR_MASK \
    0x000000FFU
#define I3C_DEV_CHAR_TABLE2_LOC3_DCR_POS    0U

/* Bit fields of DEV_CHAR_TABLE2_LOC4 register */
#define I3C_DEV_CHAR_TABLE2_LOC4_DEV_DYNAMIC_ADDR_MASK \
    0x000000FFU
#define I3C_DEV_CHAR_TABLE2_LOC4_DEV_DYNAMIC_ADDR_POS    0U

/* Bit fields of DEV_CHAR_TABLE3_LOC1 register */
#define I3C_DEV_CHAR_TABLE3_LOC1_LSB_PROVISIONAL_ID_MASK \
    0xFFFFFFFFU
#define I3C_DEV_CHAR_TABLE3_LOC1_LSB_PROVISIONAL_ID_POS    0U

/* Bit fields of DEV_CHAR_TABLE3_LOC2 register */
#define I3C_DEV_CHAR_TABLE3_LOC2_MSB_PROVISIONAL_ID_MASK \
    0x0000FFFFU
#define I3C_DEV_CHAR_TABLE3_LOC2_MSB_PROVISIONAL_ID_POS    0U

/* Bit fields of DEV_CHAR_TABLE3_LOC3 register */
#define I3C_DEV_CHAR_TABLE3_LOC3_BCR_MASK \
    0x0000FF00U
#define I3C_DEV_CHAR_TABLE3_LOC3_BCR_POS    8U
#define I3C_DEV_CHAR_TABLE3_LOC3_DCR_MASK \
    0x000000FFU
#define I3C_DEV_CHAR_TABLE3_LOC3_DCR_POS    0U

/* Bit fields of DEV_CHAR_TABLE3_LOC4 register */
#define I3C_DEV_CHAR_TABLE3_LOC4_DEV_DYNAMIC_ADDR_MASK \
    0x000000FFU
#define I3C_DEV_CHAR_TABLE3_LOC4_DEV_DYNAMIC_ADDR_POS    0U

/* Bit fields of DEV_CHAR_TABLE4_LOC1 register */
#define I3C_DEV_CHAR_TABLE4_LOC1_LSB_PROVISIONAL_ID_MASK \
    0xFFFFFFFFU
#define I3C_DEV_CHAR_TABLE4_LOC1_LSB_PROVISIONAL_ID_POS    0U

/* Bit fields of DEV_CHAR_TABLE4_LOC2 register */
#define I3C_DEV_CHAR_TABLE4_LOC2_MSB_PROVISIONAL_ID_MASK \
    0x0000FFFFU
#define I3C_DEV_CHAR_TABLE4_LOC2_MSB_PROVISIONAL_ID_POS    0U

/* Bit fields of DEV_CHAR_TABLE4_LOC3 register */
#define I3C_DEV_CHAR_TABLE4_LOC3_BCR_MASK \
    0x0000FF00U
#define I3C_DEV_CHAR_TABLE4_LOC3_BCR_POS    8U
#define I3C_DEV_CHAR_TABLE4_LOC3_DCR_MASK \
    0x000000FFU
#define I3C_DEV_CHAR_TABLE4_LOC3_DCR_POS    0U

/* Bit fields of DEV_CHAR_TABLE4_LOC4 register */
#define I3C_DEV_CHAR_TABLE4_LOC4_DEV_DYNAMIC_ADDR_MASK \
    0x000000FFU
#define I3C_DEV_CHAR_TABLE4_LOC4_DEV_DYNAMIC_ADDR_POS    0U

/* Bit fields of DEV_CHAR_TABLE5_LOC1 register */
#define I3C_DEV_CHAR_TABLE5_LOC1_LSB_PROVISIONAL_ID_MASK \
    0xFFFFFFFFU
#define I3C_DEV_CHAR_TABLE5_LOC1_LSB_PROVISIONAL_ID_POS    0U

/* Bit fields of DEV_CHAR_TABLE5_LOC2 register */
#define I3C_DEV_CHAR_TABLE5_LOC2_MSB_PROVISIONAL_ID_MASK \
    0x0000FFFFU
#define I3C_DEV_CHAR_TABLE5_LOC2_MSB_PROVISIONAL_ID_POS    0U

/* Bit fields of DEV_CHAR_TABLE5_LOC3 register */
#define I3C_DEV_CHAR_TABLE5_LOC3_BCR_MASK \
    0x0000FF00U
#define I3C_DEV_CHAR_TABLE5_LOC3_BCR_POS    8U
#define I3C_DEV_CHAR_TABLE5_LOC3_DCR_MASK \
    0x000000FFU
#define I3C_DEV_CHAR_TABLE5_LOC3_DCR_POS    0U

/* Bit fields of DEV_CHAR_TABLE5_LOC4 register */
#define I3C_DEV_CHAR_TABLE5_LOC4_DEV_DYNAMIC_ADDR_MASK \
    0x000000FFU
#define I3C_DEV_CHAR_TABLE5_LOC4_DEV_DYNAMIC_ADDR_POS    0U

/* Bit fields of DEV_CHAR_TABLE6_LOC1 register */
#define I3C_DEV_CHAR_TABLE6_LOC1_LSB_PROVISIONAL_ID_MASK \
    0xFFFFFFFFU
#define I3C_DEV_CHAR_TABLE6_LOC1_LSB_PROVISIONAL_ID_POS    0U

/* Bit fields of DEV_CHAR_TABLE6_LOC2 register */
#define I3C_DEV_CHAR_TABLE6_LOC2_MSB_PROVISIONAL_ID_MASK \
    0x0000FFFFU
#define I3C_DEV_CHAR_TABLE6_LOC2_MSB_PROVISIONAL_ID_POS    0U

/* Bit fields of DEV_CHAR_TABLE6_LOC3 register */
#define I3C_DEV_CHAR_TABLE6_LOC3_BCR_MASK \
    0x0000FF00U
#define I3C_DEV_CHAR_TABLE6_LOC3_BCR_POS    8U
#define I3C_DEV_CHAR_TABLE6_LOC3_DCR_MASK \
    0x000000FFU
#define I3C_DEV_CHAR_TABLE6_LOC3_DCR_POS    0U

/* Bit fields of DEV_CHAR_TABLE6_LOC4 register */
#define I3C_DEV_CHAR_TABLE6_LOC4_DEV_DYNAMIC_ADDR_MASK \
    0x000000FFU
#define I3C_DEV_CHAR_TABLE6_LOC4_DEV_DYNAMIC_ADDR_POS    0U

/* Bit fields of DEV_CHAR_TABLE7_LOC1 register */
#define I3C_DEV_CHAR_TABLE7_LOC1_LSB_PROVISIONAL_ID_MASK \
    0xFFFFFFFFU
#define I3C_DEV_CHAR_TABLE7_LOC1_LSB_PROVISIONAL_ID_POS    0U

/* Bit fields of DEV_CHAR_TABLE7_LOC2 register */
#define I3C_DEV_CHAR_TABLE7_LOC2_MSB_PROVISIONAL_ID_MASK \
    0x0000FFFFU
#define I3C_DEV_CHAR_TABLE7_LOC2_MSB_PROVISIONAL_ID_POS    0U

/* Bit fields of DEV_CHAR_TABLE7_LOC3 register */
#define I3C_DEV_CHAR_TABLE7_LOC3_BCR_MASK \
    0x0000FF00U
#define I3C_DEV_CHAR_TABLE7_LOC3_BCR_POS    8U
#define I3C_DEV_CHAR_TABLE7_LOC3_DCR_MASK \
    0x000000FFU
#define I3C_DEV_CHAR_TABLE7_LOC3_DCR_POS    0U

/* Bit fields of DEV_CHAR_TABLE7_LOC4 register */
#define I3C_DEV_CHAR_TABLE7_LOC4_DEV_DYNAMIC_ADDR_MASK \
    0x000000FFU
#define I3C_DEV_CHAR_TABLE7_LOC4_DEV_DYNAMIC_ADDR_POS    0U

/* Bit fields of DEV_CHAR_TABLE8_LOC1 register */
#define I3C_DEV_CHAR_TABLE8_LOC1_LSB_PROVISIONAL_ID_MASK \
    0xFFFFFFFFU
#define I3C_DEV_CHAR_TABLE8_LOC1_LSB_PROVISIONAL_ID_POS    0U

/* Bit fields of DEV_CHAR_TABLE8_LOC2 register */
#define I3C_DEV_CHAR_TABLE8_LOC2_MSB_PROVISIONAL_ID_MASK \
    0x0000FFFFU
#define I3C_DEV_CHAR_TABLE8_LOC2_MSB_PROVISIONAL_ID_POS    0U

/* Bit fields of DEV_CHAR_TABLE8_LOC3 register */
#define I3C_DEV_CHAR_TABLE8_LOC3_BCR_MASK \
    0x0000FF00U
#define I3C_DEV_CHAR_TABLE8_LOC3_BCR_POS    8U
#define I3C_DEV_CHAR_TABLE8_LOC3_DCR_MASK \
    0x000000FFU
#define I3C_DEV_CHAR_TABLE8_LOC3_DCR_POS    0U

/* Bit fields of DEV_CHAR_TABLE8_LOC4 register */
#define I3C_DEV_CHAR_TABLE8_LOC4_DEV_DYNAMIC_ADDR_MASK \
    0x000000FFU
#define I3C_DEV_CHAR_TABLE8_LOC4_DEV_DYNAMIC_ADDR_POS    0U

/* Bit fields of DEV_ADDR_TABLE1_LOC1 register */
#define I3C_DEV_ADDR_TABLE1_LOC1_DEVICE_MASK \
    0x80000000U
#define I3C_DEV_ADDR_TABLE1_LOC1_DEVICE_POS                31U
#define I3C_DEV_ADDR_TABLE1_LOC1_DEV_NACK_RETRY_CNT_MASK \
    0x60000000U
#define I3C_DEV_ADDR_TABLE1_LOC1_DEV_NACK_RETRY_CNT_POS    29U
#define I3C_DEV_ADDR_TABLE1_LOC1_DEV_DYNAMIC_ADDR_MASK \
    0x00FF0000U
#define I3C_DEV_ADDR_TABLE1_LOC1_DEV_DYNAMIC_ADDR_POS      16U
#define I3C_DEV_ADDR_TABLE1_LOC1_MR_REJECT_MASK \
    0x00004000U
#define I3C_DEV_ADDR_TABLE1_LOC1_MR_REJECT_POS             14U
#define I3C_DEV_ADDR_TABLE1_LOC1_SIR_REJECT_MASK \
    0x00002000U
#define I3C_DEV_ADDR_TABLE1_LOC1_SIR_REJECT_POS            13U
#define I3C_DEV_ADDR_TABLE1_LOC1_IBI_WITH_DATA_MASK \
    0x00001000U
#define I3C_DEV_ADDR_TABLE1_LOC1_IBI_WITH_DATA_POS         12U
#define I3C_DEV_ADDR_TABLE1_LOC1_IBI_PEC_EN_MASK \
    0x00000800U
#define I3C_DEV_ADDR_TABLE1_LOC1_IBI_PEC_EN_POS            11U
#define I3C_DEV_ADDR_TABLE1_LOC1_STATIC_ADDRESS_MASK \
    0x0000007FU
#define I3C_DEV_ADDR_TABLE1_LOC1_STATIC_ADDRESS_POS        0U

/* Bit fields of DEV_ADDR_TABLE2_LOC1 register */
#define I3C_DEV_ADDR_TABLE2_LOC1_DEVICE_MASK \
    0x80000000U
#define I3C_DEV_ADDR_TABLE2_LOC1_DEVICE_POS                31U
#define I3C_DEV_ADDR_TABLE2_LOC1_DEV_NACK_RETRY_CNT_MASK \
    0x60000000U
#define I3C_DEV_ADDR_TABLE2_LOC1_DEV_NACK_RETRY_CNT_POS    29U
#define I3C_DEV_ADDR_TABLE2_LOC1_DEV_DYNAMIC_ADDR_MASK \
    0x00FF0000U
#define I3C_DEV_ADDR_TABLE2_LOC1_DEV_DYNAMIC_ADDR_POS      16U
#define I3C_DEV_ADDR_TABLE2_LOC1_MR_REJECT_MASK \
    0x00004000U
#define I3C_DEV_ADDR_TABLE2_LOC1_MR_REJECT_POS             14U
#define I3C_DEV_ADDR_TABLE2_LOC1_SIR_REJECT_MASK \
    0x00002000U
#define I3C_DEV_ADDR_TABLE2_LOC1_SIR_REJECT_POS            13U
#define I3C_DEV_ADDR_TABLE2_LOC1_IBI_WITH_DATA_MASK \
    0x00001000U
#define I3C_DEV_ADDR_TABLE2_LOC1_IBI_WITH_DATA_POS         12U
#define I3C_DEV_ADDR_TABLE2_LOC1_IBI_PEC_EN_MASK \
    0x00000800U
#define I3C_DEV_ADDR_TABLE2_LOC1_IBI_PEC_EN_POS            11U
#define I3C_DEV_ADDR_TABLE2_LOC1_STATIC_ADDRESS_MASK \
    0x0000007FU
#define I3C_DEV_ADDR_TABLE2_LOC1_STATIC_ADDRESS_POS        0U

/* Bit fields of DEV_ADDR_TABLE3_LOC1 register */
#define I3C_DEV_ADDR_TABLE3_LOC1_DEVICE_MASK \
    0x80000000U
#define I3C_DEV_ADDR_TABLE3_LOC1_DEVICE_POS                31U
#define I3C_DEV_ADDR_TABLE3_LOC1_DEV_NACK_RETRY_CNT_MASK \
    0x60000000U
#define I3C_DEV_ADDR_TABLE3_LOC1_DEV_NACK_RETRY_CNT_POS    29U
#define I3C_DEV_ADDR_TABLE3_LOC1_DEV_DYNAMIC_ADDR_MASK \
    0x00FF0000U
#define I3C_DEV_ADDR_TABLE3_LOC1_DEV_DYNAMIC_ADDR_POS      16U
#define I3C_DEV_ADDR_TABLE3_LOC1_MR_REJECT_MASK \
    0x00004000U
#define I3C_DEV_ADDR_TABLE3_LOC1_MR_REJECT_POS             14U
#define I3C_DEV_ADDR_TABLE3_LOC1_SIR_REJECT_MASK \
    0x00002000U
#define I3C_DEV_ADDR_TABLE3_LOC1_SIR_REJECT_POS            13U
#define I3C_DEV_ADDR_TABLE3_LOC1_IBI_WITH_DATA_MASK \
    0x00001000U
#define I3C_DEV_ADDR_TABLE3_LOC1_IBI_WITH_DATA_POS         12U
#define I3C_DEV_ADDR_TABLE3_LOC1_IBI_PEC_EN_MASK \
    0x00000800U
#define I3C_DEV_ADDR_TABLE3_LOC1_IBI_PEC_EN_POS            11U
#define I3C_DEV_ADDR_TABLE3_LOC1_STATIC_ADDRESS_MASK \
    0x0000007FU
#define I3C_DEV_ADDR_TABLE3_LOC1_STATIC_ADDRESS_POS        0U

/* Bit fields of DEV_ADDR_TABLE4_LOC1 register */
#define I3C_DEV_ADDR_TABLE4_LOC1_DEVICE_MASK \
    0x80000000U
#define I3C_DEV_ADDR_TABLE4_LOC1_DEVICE_POS                31U
#define I3C_DEV_ADDR_TABLE4_LOC1_DEV_NACK_RETRY_CNT_MASK \
    0x60000000U
#define I3C_DEV_ADDR_TABLE4_LOC1_DEV_NACK_RETRY_CNT_POS    29U
#define I3C_DEV_ADDR_TABLE4_LOC1_DEV_DYNAMIC_ADDR_MASK \
    0x00FF0000U
#define I3C_DEV_ADDR_TABLE4_LOC1_DEV_DYNAMIC_ADDR_POS      16U
#define I3C_DEV_ADDR_TABLE4_LOC1_MR_REJECT_MASK \
    0x00004000U
#define I3C_DEV_ADDR_TABLE4_LOC1_MR_REJECT_POS             14U
#define I3C_DEV_ADDR_TABLE4_LOC1_SIR_REJECT_MASK \
    0x00002000U
#define I3C_DEV_ADDR_TABLE4_LOC1_SIR_REJECT_POS            13U
#define I3C_DEV_ADDR_TABLE4_LOC1_IBI_WITH_DATA_MASK \
    0x00001000U
#define I3C_DEV_ADDR_TABLE4_LOC1_IBI_WITH_DATA_POS         12U
#define I3C_DEV_ADDR_TABLE4_LOC1_IBI_PEC_EN_MASK \
    0x00000800U
#define I3C_DEV_ADDR_TABLE4_LOC1_IBI_PEC_EN_POS            11U
#define I3C_DEV_ADDR_TABLE4_LOC1_STATIC_ADDRESS_MASK \
    0x0000007FU
#define I3C_DEV_ADDR_TABLE4_LOC1_STATIC_ADDRESS_POS        0U

/* Bit fields of DEV_ADDR_TABLE5_LOC1 register */
#define I3C_DEV_ADDR_TABLE5_LOC1_DEVICE_MASK \
    0x80000000U
#define I3C_DEV_ADDR_TABLE5_LOC1_DEVICE_POS                31U
#define I3C_DEV_ADDR_TABLE5_LOC1_DEV_NACK_RETRY_CNT_MASK \
    0x60000000U
#define I3C_DEV_ADDR_TABLE5_LOC1_DEV_NACK_RETRY_CNT_POS    29U
#define I3C_DEV_ADDR_TABLE5_LOC1_DEV_DYNAMIC_ADDR_MASK \
    0x00FF0000U
#define I3C_DEV_ADDR_TABLE5_LOC1_DEV_DYNAMIC_ADDR_POS      16U
#define I3C_DEV_ADDR_TABLE5_LOC1_MR_REJECT_MASK \
    0x00004000U
#define I3C_DEV_ADDR_TABLE5_LOC1_MR_REJECT_POS             14U
#define I3C_DEV_ADDR_TABLE5_LOC1_SIR_REJECT_MASK \
    0x00002000U
#define I3C_DEV_ADDR_TABLE5_LOC1_SIR_REJECT_POS            13U
#define I3C_DEV_ADDR_TABLE5_LOC1_IBI_WITH_DATA_MASK \
    0x00001000U
#define I3C_DEV_ADDR_TABLE5_LOC1_IBI_WITH_DATA_POS         12U
#define I3C_DEV_ADDR_TABLE5_LOC1_IBI_PEC_EN_MASK \
    0x00000800U
#define I3C_DEV_ADDR_TABLE5_LOC1_IBI_PEC_EN_POS            11U
#define I3C_DEV_ADDR_TABLE5_LOC1_STATIC_ADDRESS_MASK \
    0x0000007FU
#define I3C_DEV_ADDR_TABLE5_LOC1_STATIC_ADDRESS_POS        0U

/* Bit fields of DEV_ADDR_TABLE6_LOC1 register */
#define I3C_DEV_ADDR_TABLE6_LOC1_DEVICE_MASK \
    0x80000000U
#define I3C_DEV_ADDR_TABLE6_LOC1_DEVICE_POS                31U
#define I3C_DEV_ADDR_TABLE6_LOC1_DEV_NACK_RETRY_CNT_MASK \
    0x60000000U
#define I3C_DEV_ADDR_TABLE6_LOC1_DEV_NACK_RETRY_CNT_POS    29U
#define I3C_DEV_ADDR_TABLE6_LOC1_DEV_DYNAMIC_ADDR_MASK \
    0x00FF0000U
#define I3C_DEV_ADDR_TABLE6_LOC1_DEV_DYNAMIC_ADDR_POS      16U
#define I3C_DEV_ADDR_TABLE6_LOC1_MR_REJECT_MASK \
    0x00004000U
#define I3C_DEV_ADDR_TABLE6_LOC1_MR_REJECT_POS             14U
#define I3C_DEV_ADDR_TABLE6_LOC1_SIR_REJECT_MASK \
    0x00002000U
#define I3C_DEV_ADDR_TABLE6_LOC1_SIR_REJECT_POS            13U
#define I3C_DEV_ADDR_TABLE6_LOC1_IBI_WITH_DATA_MASK \
    0x00001000U
#define I3C_DEV_ADDR_TABLE6_LOC1_IBI_WITH_DATA_POS         12U
#define I3C_DEV_ADDR_TABLE6_LOC1_IBI_PEC_EN_MASK \
    0x00000800U
#define I3C_DEV_ADDR_TABLE6_LOC1_IBI_PEC_EN_POS            11U
#define I3C_DEV_ADDR_TABLE6_LOC1_STATIC_ADDRESS_MASK \
    0x0000007FU
#define I3C_DEV_ADDR_TABLE6_LOC1_STATIC_ADDRESS_POS        0U

/* Bit fields of DEV_ADDR_TABLE7_LOC1 register */
#define I3C_DEV_ADDR_TABLE7_LOC1_DEVICE_MASK \
    0x80000000U
#define I3C_DEV_ADDR_TABLE7_LOC1_DEVICE_POS                31U
#define I3C_DEV_ADDR_TABLE7_LOC1_DEV_NACK_RETRY_CNT_MASK \
    0x60000000U
#define I3C_DEV_ADDR_TABLE7_LOC1_DEV_NACK_RETRY_CNT_POS    29U
#define I3C_DEV_ADDR_TABLE7_LOC1_DEV_DYNAMIC_ADDR_MASK \
    0x00FF0000U
#define I3C_DEV_ADDR_TABLE7_LOC1_DEV_DYNAMIC_ADDR_POS      16U
#define I3C_DEV_ADDR_TABLE7_LOC1_MR_REJECT_MASK \
    0x00004000U
#define I3C_DEV_ADDR_TABLE7_LOC1_MR_REJECT_POS             14U
#define I3C_DEV_ADDR_TABLE7_LOC1_SIR_REJECT_MASK \
    0x00002000U
#define I3C_DEV_ADDR_TABLE7_LOC1_SIR_REJECT_POS            13U
#define I3C_DEV_ADDR_TABLE7_LOC1_IBI_WITH_DATA_MASK \
    0x00001000U
#define I3C_DEV_ADDR_TABLE7_LOC1_IBI_WITH_DATA_POS         12U
#define I3C_DEV_ADDR_TABLE7_LOC1_IBI_PEC_EN_MASK \
    0x00000800U
#define I3C_DEV_ADDR_TABLE7_LOC1_IBI_PEC_EN_POS            11U
#define I3C_DEV_ADDR_TABLE7_LOC1_STATIC_ADDRESS_MASK \
    0x0000007FU
#define I3C_DEV_ADDR_TABLE7_LOC1_STATIC_ADDRESS_POS        0U

/* Bit fields of DEV_ADDR_TABLE8_LOC1 register */
#define I3C_DEV_ADDR_TABLE8_LOC1_DEVICE_MASK \
    0x80000000U
#define I3C_DEV_ADDR_TABLE8_LOC1_DEVICE_POS                31U
#define I3C_DEV_ADDR_TABLE8_LOC1_DEV_NACK_RETRY_CNT_MASK \
    0x60000000U
#define I3C_DEV_ADDR_TABLE8_LOC1_DEV_NACK_RETRY_CNT_POS    29U
#define I3C_DEV_ADDR_TABLE8_LOC1_DEV_DYNAMIC_ADDR_MASK \
    0x00FF0000U
#define I3C_DEV_ADDR_TABLE8_LOC1_DEV_DYNAMIC_ADDR_POS      16U
#define I3C_DEV_ADDR_TABLE8_LOC1_MR_REJECT_MASK \
    0x00004000U
#define I3C_DEV_ADDR_TABLE8_LOC1_MR_REJECT_POS             14U
#define I3C_DEV_ADDR_TABLE8_LOC1_SIR_REJECT_MASK \
    0x00002000U
#define I3C_DEV_ADDR_TABLE8_LOC1_SIR_REJECT_POS            13U
#define I3C_DEV_ADDR_TABLE8_LOC1_IBI_WITH_DATA_MASK \
    0x00001000U
#define I3C_DEV_ADDR_TABLE8_LOC1_IBI_WITH_DATA_POS         12U
#define I3C_DEV_ADDR_TABLE8_LOC1_IBI_PEC_EN_MASK \
    0x00000800U
#define I3C_DEV_ADDR_TABLE8_LOC1_IBI_PEC_EN_POS            11U
#define I3C_DEV_ADDR_TABLE8_LOC1_STATIC_ADDRESS_MASK \
    0x0000007FU
#define I3C_DEV_ADDR_TABLE8_LOC1_STATIC_ADDRESS_POS        0U

/* Bit fields of DEV_ADDR_TABLE9_LOC1 register */
#define I3C_DEV_ADDR_TABLE9_LOC1_DEVICE_MASK \
    0x80000000U
#define I3C_DEV_ADDR_TABLE9_LOC1_DEVICE_POS                31U
#define I3C_DEV_ADDR_TABLE9_LOC1_DEV_NACK_RETRY_CNT_MASK \
    0x60000000U
#define I3C_DEV_ADDR_TABLE9_LOC1_DEV_NACK_RETRY_CNT_POS    29U
#define I3C_DEV_ADDR_TABLE9_LOC1_DEV_DYNAMIC_ADDR_MASK \
    0x00FF0000U
#define I3C_DEV_ADDR_TABLE9_LOC1_DEV_DYNAMIC_ADDR_POS      16U
#define I3C_DEV_ADDR_TABLE9_LOC1_MR_REJECT_MASK \
    0x00004000U
#define I3C_DEV_ADDR_TABLE9_LOC1_MR_REJECT_POS             14U
#define I3C_DEV_ADDR_TABLE9_LOC1_SIR_REJECT_MASK \
    0x00002000U
#define I3C_DEV_ADDR_TABLE9_LOC1_SIR_REJECT_POS            13U
#define I3C_DEV_ADDR_TABLE9_LOC1_IBI_WITH_DATA_MASK \
    0x00001000U
#define I3C_DEV_ADDR_TABLE9_LOC1_IBI_WITH_DATA_POS         12U
#define I3C_DEV_ADDR_TABLE9_LOC1_IBI_PEC_EN_MASK \
    0x00000800U
#define I3C_DEV_ADDR_TABLE9_LOC1_IBI_PEC_EN_POS            11U
#define I3C_DEV_ADDR_TABLE9_LOC1_STATIC_ADDRESS_MASK \
    0x0000007FU
#define I3C_DEV_ADDR_TABLE9_LOC1_STATIC_ADDRESS_POS        0U

/* Bit fields of DEV_ADDR_TABLE10_LOC1 register */
#define I3C_DEV_ADDR_TABLE10_LOC1_DEVICE_MASK \
    0x80000000U
#define I3C_DEV_ADDR_TABLE10_LOC1_DEVICE_POS                31U
#define I3C_DEV_ADDR_TABLE10_LOC1_DEV_NACK_RETRY_CNT_MASK \
    0x60000000U
#define I3C_DEV_ADDR_TABLE10_LOC1_DEV_NACK_RETRY_CNT_POS    29U
#define I3C_DEV_ADDR_TABLE10_LOC1_DEV_DYNAMIC_ADDR_MASK \
    0x00FF0000U
#define I3C_DEV_ADDR_TABLE10_LOC1_DEV_DYNAMIC_ADDR_POS      16U
#define I3C_DEV_ADDR_TABLE10_LOC1_MR_REJECT_MASK \
    0x00004000U
#define I3C_DEV_ADDR_TABLE10_LOC1_MR_REJECT_POS             14U
#define I3C_DEV_ADDR_TABLE10_LOC1_SIR_REJECT_MASK \
    0x00002000U
#define I3C_DEV_ADDR_TABLE10_LOC1_SIR_REJECT_POS            13U
#define I3C_DEV_ADDR_TABLE10_LOC1_IBI_WITH_DATA_MASK \
    0x00001000U
#define I3C_DEV_ADDR_TABLE10_LOC1_IBI_WITH_DATA_POS         12U
#define I3C_DEV_ADDR_TABLE10_LOC1_IBI_PEC_EN_MASK \
    0x00000800U
#define I3C_DEV_ADDR_TABLE10_LOC1_IBI_PEC_EN_POS            11U
#define I3C_DEV_ADDR_TABLE10_LOC1_STATIC_ADDRESS_MASK \
    0x0000007FU
#define I3C_DEV_ADDR_TABLE10_LOC1_STATIC_ADDRESS_POS        0U

/* Bit fields of DEV_ADDR_TABLE11_LOC1 register */
#define I3C_DEV_ADDR_TABLE11_LOC1_DEVICE_MASK \
    0x80000000U
#define I3C_DEV_ADDR_TABLE11_LOC1_DEVICE_POS                31U
#define I3C_DEV_ADDR_TABLE11_LOC1_DEV_NACK_RETRY_CNT_MASK \
    0x60000000U
#define I3C_DEV_ADDR_TABLE11_LOC1_DEV_NACK_RETRY_CNT_POS    29U
#define I3C_DEV_ADDR_TABLE11_LOC1_DEV_DYNAMIC_ADDR_MASK \
    0x00FF0000U
#define I3C_DEV_ADDR_TABLE11_LOC1_DEV_DYNAMIC_ADDR_POS      16U
#define I3C_DEV_ADDR_TABLE11_LOC1_MR_REJECT_MASK \
    0x00004000U
#define I3C_DEV_ADDR_TABLE11_LOC1_MR_REJECT_POS             14U
#define I3C_DEV_ADDR_TABLE11_LOC1_SIR_REJECT_MASK \
    0x00002000U
#define I3C_DEV_ADDR_TABLE11_LOC1_SIR_REJECT_POS            13U
#define I3C_DEV_ADDR_TABLE11_LOC1_IBI_WITH_DATA_MASK \
    0x00001000U
#define I3C_DEV_ADDR_TABLE11_LOC1_IBI_WITH_DATA_POS         12U
#define I3C_DEV_ADDR_TABLE11_LOC1_IBI_PEC_EN_MASK \
    0x00000800U
#define I3C_DEV_ADDR_TABLE11_LOC1_IBI_PEC_EN_POS            11U
#define I3C_DEV_ADDR_TABLE11_LOC1_STATIC_ADDRESS_MASK \
    0x0000007FU
#define I3C_DEV_ADDR_TABLE11_LOC1_STATIC_ADDRESS_POS        0U


#endif  //__SOCFPGA_I3C_REGS_H__
